version: "2017-09-20"
pipeline:
  - id: build
    type: script
    env:
      IMAGE: pierone.stups.zalan.do/pitchfork/yourturn
    commands:
      - desc: Install Docker
        cmd: |
          curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
          apt-get update -yq && apt-get install -yq nodejs
      - desc: Build and push Docker image
        cmd: |
          npm install --global gulp-cli
          npm i

          cd client
          gulp build
          gulp lint
          gulp format

          cd ..
          time docker build -t ${IMAGE}-test:${CDP_BUILD_VERSION} \
                            -t ${IMAGE}:${CDP_BUILD_VERSION} .


          IS_PR_BUILD=${CDP_PULL_REQUEST_NUMBER+"true"}
          if [[ ${CDP_TARGET_BRANCH} == "master" && ${IS_PR_BUILD} != "true" ]]; then
              docker push ${IMAGE}:${CDP_BUILD_VERSION}
          else
              docker push ${IMAGE}-test:${CDP_BUILD_VERSION}
          fi

